package genki.utils;

public enum UpdateStatus {

    USERNAME_UPDATED,
    BIO_UPDATED,
    PASSWORD_UPDATED,
    PHOTO_UPDATED,
    INVALID_USERNAME,
    INVALID_CURRENT_PASSWORD,
    INVALID_NEW_PASSWORD,
    DB_ERROR,
    IMG_UPLOAD_ERROR
}
