package genki.utils;

public enum UpdateStatus {

    USERNAME_UPDATED,
    BIO_UPDATED,
    PASSWORD_UPDATED,
    PHOTO_UPDATED,
    INVALID_USERNAME,
    INVALID_CURRENT_PASSWORD,
    INVALID_NEW_PASSWORD,
    DB_ERROR,
    IMG_UPLOAD_ERROR,
    ACCOUNT_DELETED,
    ACCOUNT_DELETION_ERROR,
    GROUP_NAME_UPDATED,
    GROUP_DESCRIPTION_UPDATED,
    GROUP_VISIBILITY_UPDATED,
    GROUP_DELETED,
    GROUP_DELETION_ERROR
}
